// COPYRIGHT (C) HARRY CLARK 2025
// LIGHTWEIGHT CODE EMITTER/GENERATOR FOR THE HITACHI SUPERH2

// THIS FILE PERTAINS TOWARDS THE FUNCTIONALITY ENCOMPASSING THE DMA CONTROL
// DETERMINING THE CIRCUMSTANCES BY WHICH OPERATIONS OFTEN CONTROL THE FLOW OF DMA BETWEEN OPERANDS

#pragma once

// NESTED INCLUDES

#include <common.h>
#include <reg.hh>

class SH2_DMAC
{
    private:
        enum class SH2_DMA_MODE { FIXED, INCREMENT, DECREMENT, RESVERSE };
};